version: "3.7"

x-base: &base
  env_file:
    - ./.env

services:

  auth:
    <<: *base
    container_name: "auth"
    build:
      ./
    ports:
      - "${AUTH_PORT}:${DEFAULT_PORT}"

  db:
    container_name: "postgres"
    image: postgres
    env_file:
      - ./.env
    ports:
      - "5432:5432"
